package net.jeeshop.biz.product.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProcessInfoExample {
    protected String orderByClause;

    protected boolean distinct;

    protected List<Criteria> oredCriteria;

    public ProcessInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pro_process
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNewnumIdIsNull() {
            addCriterion("newnum_id is null");
            return (Criteria) this;
        }

        public Criteria andNewnumIdIsNotNull() {
            addCriterion("newnum_id is not null");
            return (Criteria) this;
        }

        public Criteria andNewnumIdEqualTo(Integer value) {
            addCriterion("newnum_id =", value, "newnumId");
            return (Criteria) this;
        }

        public Criteria andNewnumIdNotEqualTo(Integer value) {
            addCriterion("newnum_id <>", value, "newnumId");
            return (Criteria) this;
        }

        public Criteria andNewnumIdGreaterThan(Integer value) {
            addCriterion("newnum_id >", value, "newnumId");
            return (Criteria) this;
        }

        public Criteria andNewnumIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("newnum_id >=", value, "newnumId");
            return (Criteria) this;
        }

        public Criteria andNewnumIdLessThan(Integer value) {
            addCriterion("newnum_id <", value, "newnumId");
            return (Criteria) this;
        }

        public Criteria andNewnumIdLessThanOrEqualTo(Integer value) {
            addCriterion("newnum_id <=", value, "newnumId");
            return (Criteria) this;
        }

        public Criteria andNewnumIdIn(List<Integer> values) {
            addCriterion("newnum_id in", values, "newnumId");
            return (Criteria) this;
        }

        public Criteria andNewnumIdNotIn(List<Integer> values) {
            addCriterion("newnum_id not in", values, "newnumId");
            return (Criteria) this;
        }

        public Criteria andNewnumIdBetween(Integer value1, Integer value2) {
            addCriterion("newnum_id between", value1, value2, "newnumId");
            return (Criteria) this;
        }

        public Criteria andNewnumIdNotBetween(Integer value1, Integer value2) {
            addCriterion("newnum_id not between", value1, value2, "newnumId");
            return (Criteria) this;
        }

        public Criteria andNewnumsIsNull() {
            addCriterion("newnums is null");
            return (Criteria) this;
        }

        public Criteria andNewnumsIsNotNull() {
            addCriterion("newnums is not null");
            return (Criteria) this;
        }

        public Criteria andNewnumsEqualTo(Integer value) {
            addCriterion("newnums =", value, "newnums");
            return (Criteria) this;
        }

        public Criteria andNewnumsNotEqualTo(Integer value) {
            addCriterion("newnums <>", value, "newnums");
            return (Criteria) this;
        }

        public Criteria andNewnumsGreaterThan(Integer value) {
            addCriterion("newnums >", value, "newnums");
            return (Criteria) this;
        }

        public Criteria andNewnumsGreaterThanOrEqualTo(Integer value) {
            addCriterion("newnums >=", value, "newnums");
            return (Criteria) this;
        }

        public Criteria andNewnumsLessThan(Integer value) {
            addCriterion("newnums <", value, "newnums");
            return (Criteria) this;
        }

        public Criteria andNewnumsLessThanOrEqualTo(Integer value) {
            addCriterion("newnums <=", value, "newnums");
            return (Criteria) this;
        }

        public Criteria andNewnumsIn(List<Integer> values) {
            addCriterion("newnums in", values, "newnums");
            return (Criteria) this;
        }

        public Criteria andNewnumsNotIn(List<Integer> values) {
            addCriterion("newnums not in", values, "newnums");
            return (Criteria) this;
        }

        public Criteria andNewnumsBetween(Integer value1, Integer value2) {
            addCriterion("newnums between", value1, value2, "newnums");
            return (Criteria) this;
        }

        public Criteria andNewnumsNotBetween(Integer value1, Integer value2) {
            addCriterion("newnums not between", value1, value2, "newnums");
            return (Criteria) this;
        }

        public Criteria andOldnumIdIsNull() {
            addCriterion("oldnum_id is null");
            return (Criteria) this;
        }

        public Criteria andOldnumIdIsNotNull() {
            addCriterion("oldnum_id is not null");
            return (Criteria) this;
        }

        public Criteria andOldnumIdEqualTo(Integer value) {
            addCriterion("oldnum_id =", value, "oldnumId");
            return (Criteria) this;
        }

        public Criteria andOldnumIdNotEqualTo(Integer value) {
            addCriterion("oldnum_id <>", value, "oldnumId");
            return (Criteria) this;
        }

        public Criteria andOldnumIdGreaterThan(Integer value) {
            addCriterion("oldnum_id >", value, "oldnumId");
            return (Criteria) this;
        }

        public Criteria andOldnumIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("oldnum_id >=", value, "oldnumId");
            return (Criteria) this;
        }

        public Criteria andOldnumIdLessThan(Integer value) {
            addCriterion("oldnum_id <", value, "oldnumId");
            return (Criteria) this;
        }

        public Criteria andOldnumIdLessThanOrEqualTo(Integer value) {
            addCriterion("oldnum_id <=", value, "oldnumId");
            return (Criteria) this;
        }

        public Criteria andOldnumIdIn(List<Integer> values) {
            addCriterion("oldnum_id in", values, "oldnumId");
            return (Criteria) this;
        }

        public Criteria andOldnumIdNotIn(List<Integer> values) {
            addCriterion("oldnum_id not in", values, "oldnumId");
            return (Criteria) this;
        }

        public Criteria andOldnumIdBetween(Integer value1, Integer value2) {
            addCriterion("oldnum_id between", value1, value2, "oldnumId");
            return (Criteria) this;
        }

        public Criteria andOldnumIdNotBetween(Integer value1, Integer value2) {
            addCriterion("oldnum_id not between", value1, value2, "oldnumId");
            return (Criteria) this;
        }

        public Criteria andPackageidIsNull() {
            addCriterion("packageid is null");
            return (Criteria) this;
        }

        public Criteria andPackageidIsNotNull() {
            addCriterion("packageid is not null");
            return (Criteria) this;
        }

        public Criteria andPackageidEqualTo(Integer value) {
            addCriterion("packageid =", value, "packageid");
            return (Criteria) this;
        }

        public Criteria andPackageidNotEqualTo(Integer value) {
            addCriterion("packageid <>", value, "packageid");
            return (Criteria) this;
        }

        public Criteria andPackageidGreaterThan(Integer value) {
            addCriterion("packageid >", value, "packageid");
            return (Criteria) this;
        }

        public Criteria andPackageidGreaterThanOrEqualTo(Integer value) {
            addCriterion("packageid >=", value, "packageid");
            return (Criteria) this;
        }

        public Criteria andPackageidLessThan(Integer value) {
            addCriterion("packageid <", value, "packageid");
            return (Criteria) this;
        }

        public Criteria andPackageidLessThanOrEqualTo(Integer value) {
            addCriterion("packageid <=", value, "packageid");
            return (Criteria) this;
        }

        public Criteria andPackageidIn(List<Integer> values) {
            addCriterion("packageid in", values, "packageid");
            return (Criteria) this;
        }

        public Criteria andPackageidNotIn(List<Integer> values) {
            addCriterion("packageid not in", values, "packageid");
            return (Criteria) this;
        }

        public Criteria andPackageidBetween(Integer value1, Integer value2) {
            addCriterion("packageid between", value1, value2, "packageid");
            return (Criteria) this;
        }

        public Criteria andPackageidNotBetween(Integer value1, Integer value2) {
            addCriterion("packageid not between", value1, value2, "packageid");
            return (Criteria) this;
        }

        public Criteria andUpidcardIsNull() {
            addCriterion("upidcard is null");
            return (Criteria) this;
        }

        public Criteria andUpidcardIsNotNull() {
            addCriterion("upidcard is not null");
            return (Criteria) this;
        }

        public Criteria andUpidcardEqualTo(String value) {
            addCriterion("upidcard =", value, "upidcard");
            return (Criteria) this;
        }

        public Criteria andUpidcardNotEqualTo(String value) {
            addCriterion("upidcard <>", value, "upidcard");
            return (Criteria) this;
        }

        public Criteria andUpidcardGreaterThan(String value) {
            addCriterion("upidcard >", value, "upidcard");
            return (Criteria) this;
        }

        public Criteria andUpidcardGreaterThanOrEqualTo(String value) {
            addCriterion("upidcard >=", value, "upidcard");
            return (Criteria) this;
        }

        public Criteria andUpidcardLessThan(String value) {
            addCriterion("upidcard <", value, "upidcard");
            return (Criteria) this;
        }

        public Criteria andUpidcardLessThanOrEqualTo(String value) {
            addCriterion("upidcard <=", value, "upidcard");
            return (Criteria) this;
        }

        public Criteria andUpidcardLike(String value) {
            addCriterion("upidcard like", value, "upidcard");
            return (Criteria) this;
        }

        public Criteria andUpidcardNotLike(String value) {
            addCriterion("upidcard not like", value, "upidcard");
            return (Criteria) this;
        }

        public Criteria andUpidcardIn(List<String> values) {
            addCriterion("upidcard in", values, "upidcard");
            return (Criteria) this;
        }

        public Criteria andUpidcardNotIn(List<String> values) {
            addCriterion("upidcard not in", values, "upidcard");
            return (Criteria) this;
        }

        public Criteria andUpidcardBetween(String value1, String value2) {
            addCriterion("upidcard between", value1, value2, "upidcard");
            return (Criteria) this;
        }

        public Criteria andUpidcardNotBetween(String value1, String value2) {
            addCriterion("upidcard not between", value1, value2, "upidcard");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsertelIsNull() {
            addCriterion("usertel is null");
            return (Criteria) this;
        }

        public Criteria andUsertelIsNotNull() {
            addCriterion("usertel is not null");
            return (Criteria) this;
        }

        public Criteria andUsertelEqualTo(String value) {
            addCriterion("usertel =", value, "usertel");
            return (Criteria) this;
        }

        public Criteria andUsertelNotEqualTo(String value) {
            addCriterion("usertel <>", value, "usertel");
            return (Criteria) this;
        }

        public Criteria andUsertelGreaterThan(String value) {
            addCriterion("usertel >", value, "usertel");
            return (Criteria) this;
        }

        public Criteria andUsertelGreaterThanOrEqualTo(String value) {
            addCriterion("usertel >=", value, "usertel");
            return (Criteria) this;
        }

        public Criteria andUsertelLessThan(String value) {
            addCriterion("usertel <", value, "usertel");
            return (Criteria) this;
        }

        public Criteria andUsertelLessThanOrEqualTo(String value) {
            addCriterion("usertel <=", value, "usertel");
            return (Criteria) this;
        }

        public Criteria andUsertelLike(String value) {
            addCriterion("usertel like", value, "usertel");
            return (Criteria) this;
        }

        public Criteria andUsertelNotLike(String value) {
            addCriterion("usertel not like", value, "usertel");
            return (Criteria) this;
        }

        public Criteria andUsertelIn(List<String> values) {
            addCriterion("usertel in", values, "usertel");
            return (Criteria) this;
        }

        public Criteria andUsertelNotIn(List<String> values) {
            addCriterion("usertel not in", values, "usertel");
            return (Criteria) this;
        }

        public Criteria andUsertelBetween(String value1, String value2) {
            addCriterion("usertel between", value1, value2, "usertel");
            return (Criteria) this;
        }

        public Criteria andUsertelNotBetween(String value1, String value2) {
            addCriterion("usertel not between", value1, value2, "usertel");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userid is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userid is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(String value) {
            addCriterion("userid =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(String value) {
            addCriterion("userid <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(String value) {
            addCriterion("userid >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(String value) {
            addCriterion("userid >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(String value) {
            addCriterion("userid <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(String value) {
            addCriterion("userid <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLike(String value) {
            addCriterion("userid like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotLike(String value) {
            addCriterion("userid not like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<String> values) {
            addCriterion("userid in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<String> values) {
            addCriterion("userid not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(String value1, String value2) {
            addCriterion("userid between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(String value1, String value2) {
            addCriterion("userid not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseraddrIsNull() {
            addCriterion("useraddr is null");
            return (Criteria) this;
        }

        public Criteria andUseraddrIsNotNull() {
            addCriterion("useraddr is not null");
            return (Criteria) this;
        }

        public Criteria andUseraddrEqualTo(String value) {
            addCriterion("useraddr =", value, "useraddr");
            return (Criteria) this;
        }

        public Criteria andUseraddrNotEqualTo(String value) {
            addCriterion("useraddr <>", value, "useraddr");
            return (Criteria) this;
        }

        public Criteria andUseraddrGreaterThan(String value) {
            addCriterion("useraddr >", value, "useraddr");
            return (Criteria) this;
        }

        public Criteria andUseraddrGreaterThanOrEqualTo(String value) {
            addCriterion("useraddr >=", value, "useraddr");
            return (Criteria) this;
        }

        public Criteria andUseraddrLessThan(String value) {
            addCriterion("useraddr <", value, "useraddr");
            return (Criteria) this;
        }

        public Criteria andUseraddrLessThanOrEqualTo(String value) {
            addCriterion("useraddr <=", value, "useraddr");
            return (Criteria) this;
        }

        public Criteria andUseraddrLike(String value) {
            addCriterion("useraddr like", value, "useraddr");
            return (Criteria) this;
        }

        public Criteria andUseraddrNotLike(String value) {
            addCriterion("useraddr not like", value, "useraddr");
            return (Criteria) this;
        }

        public Criteria andUseraddrIn(List<String> values) {
            addCriterion("useraddr in", values, "useraddr");
            return (Criteria) this;
        }

        public Criteria andUseraddrNotIn(List<String> values) {
            addCriterion("useraddr not in", values, "useraddr");
            return (Criteria) this;
        }

        public Criteria andUseraddrBetween(String value1, String value2) {
            addCriterion("useraddr between", value1, value2, "useraddr");
            return (Criteria) this;
        }

        public Criteria andUseraddrNotBetween(String value1, String value2) {
            addCriterion("useraddr not between", value1, value2, "useraddr");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andKhidIsNull() {
            addCriterion("khid is null");
            return (Criteria) this;
        }

        public Criteria andKhidIsNotNull() {
            addCriterion("khid is not null");
            return (Criteria) this;
        }

        public Criteria andKhidEqualTo(String value) {
            addCriterion("khid =", value, "khid");
            return (Criteria) this;
        }

        public Criteria andKhidNotEqualTo(String value) {
            addCriterion("khid <>", value, "khid");
            return (Criteria) this;
        }

        public Criteria andKhidGreaterThan(Long value) {
            addCriterion("khid >", value, "khid");
            return (Criteria) this;
        }

        public Criteria andKhidGreaterThanOrEqualTo(Long value) {
            addCriterion("khid >=", value, "khid");
            return (Criteria) this;
        }

        public Criteria andKhidLessThan(Long value) {
            addCriterion("khid <", value, "khid");
            return (Criteria) this;
        }

        public Criteria andKhidLessThanOrEqualTo(Long value) {
            addCriterion("khid <=", value, "khid");
            return (Criteria) this;
        }

        public Criteria andKhidIn(List<Long> values) {
            addCriterion("khid in", values, "khid");
            return (Criteria) this;
        }

        public Criteria andKhidNotIn(List<Long> values) {
            addCriterion("khid not in", values, "khid");
            return (Criteria) this;
        }

        public Criteria andKhidBetween(Long value1, Long value2) {
            addCriterion("khid between", value1, value2, "khid");
            return (Criteria) this;
        }

        public Criteria andKhidNotBetween(Long value1, Long value2) {
            addCriterion("khid not between", value1, value2, "khid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pro_process
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pro_process
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}